server:
  port: 8081

spring:
  application:
    name: "solicitudes-service"
  h2:
    console:
      enabled: true
      path: "/h2"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "powerup"
    schema: "public"
    username: "postgres"
    password: "123456789"

adapter:
  restconsumer:
    url: http://localhost:8080
    timeout: 5000

# adapters:
#   r2dbc:
#     host: ${DB_HOST:localhost}
#     port: ${DB_PORT:5432}
#     database: ${DB_NAME:powerup}
#     schema: ${DB_SCHEMA:public}
#     username: ${DB_USER:postgres}
#     password: ${DB_PASSWORD:123456789}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs


# ============================
# 🔐 JWT CONFIG
# ============================
security:
  jwt:
    secretKey: "2O3n1WlTtB2X6pJ5oQ7s8R9uC0FvGhIjKlMnOpQrStUvWxYz1234567890abcdef" # clave en Base64
    expiration: 3600000 # 1 hora en milisegundos