server:
  port: 8080

spring:
  application:
    name: "solicitudes-service"
  h2:
    console:
      enabled: true
      path: "/h2"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "powerup"
    schema: "public"
    username: "postgres"
    password: "123456789"

# adapters:
#   r2dbc:
#     host: ${DB_HOST:localhost}
#     port: ${DB_PORT:5432}
#     database: ${DB_NAME:powerup}
#     schema: ${DB_SCHEMA:public}
#     username: ${DB_USER:postgres}
#     password: ${DB_PASSWORD:123456789}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
